Repository tomasvdlaan/cgi-res-frontend, pull requests merged in 2022-04, with the labels that each got.

#1 Setup React & React-Router and Created initial Structure
  .gitignore
  .idea/.gitignore
  .idea/cgi-react-frontend.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.tsx
  src/Router.tsx
  src/index.css
  src/index.tsx
  src/pages/home/HomePage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/notfound/NotFoundPage.tsx
  src/pages/overview/OverviewPage.tsx
  src/pages/overview/subpages/reservation/ReservationPage.tsx
  tsconfig.json
Labels: enhancement

#2 Changed Structure, Redid Router and Started putting in placeholder components for structure
  README.md
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.tsx
  src/Router.tsx
  src/glob-components/PlaceholderBlock.tsx
  src/index.css
  src/index.tsx
  src/pages/home/HomePage.tsx
  src/pages/issues/details/IssueDetailPage.tsx
  src/pages/issues/overview/IssuesOverviewPage.tsx
  src/pages/reservations/create/ReservationCreatePage.tsx
  src/pages/reservations/details/ReservationDetailPage.tsx
  src/pages/reservations/overview/ReservationsOverviewPage.tsx
  tailwind.config.js
Labels: enhancement

#3 Feature/tailwind setup
  src/pages/home/HomePage.tsx
  tailwind.config.js
Labels: enhancement, good first issue

#8 Fixed issue of showing a white page with unknown route
  src/Router.tsx
Labels: bug, enhancement

#7 Feature/404 page
  package-lock.json
  public/Images/404Error.png
  public/Images/Error404.png
  src/images.d.ts
  src/pages/notfound/NotFoundPage.tsx
  tsconfig.json
Labels: enhancement, good first issue

#11 Datepicker finished
  src/config.json
  src/glob-components/DatePicker.tsx
  src/hooks/useDebounce.ts
  src/pages/home/HomePage.tsx
  src/pages/login/LoginPage.tsx
Labels: enhancement
